name: sampoorna_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  avatar_glow: ^3.0.1
  provider: ^6.1.1
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.10
  firebase_core: ^2.25.4
  google_fonts: ^6.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  country_code_picker: ^3.0.0
  shake: ^2.2.0
  permission_handler: ^11.3.0
  contacts_service: ^0.6.3
  fluttertoast: ^8.2.4
  sqflite: ^2.3.2
  flutter_phone_direct_caller: ^2.1.1
  background_sms: ^0.0.4
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  flutter_local_notifications: ^16.3.2
  vibration: ^1.8.4
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  lottie: ^3.1.0
  bubble: ^1.2.1
  shimmer: ^3.0.0

#  telephony: ^0.2.0
#  flutter_background_service: ^5.0.5
#  flutter_background_service_android: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color:  "#7F669D"
  color_dark: "#1A1B18"
  #  image: assets/logos/
  #  image_dark: assets/logos/

  android_12:
    icon_background_color: "#7F669D"
    icon_background_color_dark: "#1A1B18"
  #   image: assets/logos/
  #   color: "#1A1B18"
  #  image_dark: assets/logo/
  #color_dark: "#042a49"
